"""Generate the gitignored walking-footstep PCM header for the 3DS build.

The header lands in platform/3ds/build or the repository build directory.
PCM bytes stay out of Git. A missing ROM or a missing sound writes a
zero-length slot and exits 0, so the 3DS build still runs.

Each id is soundArray[sfx_id], the same index extract_sfx uses. One-shots
are not split into loops. SFX_3F2 is past the us.v10 instrument and stays empty.
"""

from __future__ import annotations

import argparse
import struct
import sys
from dataclasses import dataclass
from pathlib import Path

from tools.banjo3ds.sfx_bank import (
    SfxBankError,
    extract_sfx,
    slice_soundfont,
    supported_versions,
)
from tools.banjo3ds.sfx_probe_asset import pcm_bytes, resolve_header_path, usable_pcm, write_header

# D_80368DF0 sound ids. Order is stable so the 3DS table can scan by id.
FOOT_SFX_IDS = (
    0x5,
    0x6,
    0x7,
    0x8,
    0xB,
    0x10,
    0x26,
    0x28,
    0x98,
    0x99,
    0xDC,
    0x123,
    0x3F2,
)

REPO_ROOT = Path(__file__).resolve().parents[2]


@dataclass(frozen=True)
class FootClip:
    sfx_id: int
    blob: bytes
    attack_volume: int | None = None
    sample_volume: int | None = None
    key_base: int | None = None
    detune: int | None = None
    omit_detune: int = 0


def _keymap(ctl: bytes, sfx_id: int) -> tuple[int, int, int]:
    """keyBase, detune, and whether keyMax bit 0x20 drops detune from unk28."""
    if len(ctl) < 8:
        raise SfxBankError("soundfont ctl is too small to read a keymap")
    bank_offset = struct.unpack_from(">I", ctl, 4)[0]
    instrument_offset = struct.unpack_from(">I", ctl, bank_offset + 12)[0]
    array_at = instrument_offset + 16
    sound_offset = struct.unpack_from(">I", ctl, array_at + sfx_id * 4)[0]
    keymap_offset = struct.unpack_from(">I", ctl, sound_offset + 4)[0]
    if keymap_offset + 6 > len(ctl):
        raise SfxBankError(f"SFX {sfx_id:#x} keymap extends past the ctl")
    key_max = ctl[keymap_offset + 3]
    key_base = ctl[keymap_offset + 4]
    detune = struct.unpack_from(">b", ctl, keymap_offset + 5)[0]
    return key_base, detune, 1 if (key_max & 0x20) else 0


def decode_clip(ctl: bytes, tbl: bytes, sfx_id: int) -> FootClip:
    info, samples = extract_sfx(ctl, tbl, sfx_id)
    if info.sound_index != sfx_id:
        raise SfxBankError(
            f"SFX {sfx_id:#x} selected soundArray index {info.sound_index:#x}"
        )
    key_base, detune, omit_detune = _keymap(ctl, sfx_id)
    if key_base != info.key_base or detune != info.detune:
        raise SfxBankError(f"SFX {sfx_id:#x} keymap does not match the sound record")
    if info.peak_abs == 0:
        raise SfxBankError(f"decoded SFX {sfx_id:#x} PCM is silent")
    blob = pcm_bytes(samples)
    if not usable_pcm(blob):
        raise SfxBankError(f"decoded SFX {sfx_id:#x} PCM is not a usable PCM16 buffer")
    return FootClip(
        sfx_id,
        blob,
        info.attack_volume,
        info.sample_volume,
        key_base,
        detune,
        omit_detune,
    )


def load_clips(ctl: bytes, tbl: bytes) -> tuple[FootClip, ...]:
    clips = []
    for sfx_id in FOOT_SFX_IDS:
        try:
            clips.append(decode_clip(ctl, tbl, sfx_id))
        except SfxBankError:
            continue
    return tuple(clips)


def load_rom_clips(root: Path) -> tuple[tuple[FootClip, ...], str]:
    for version in supported_versions():
        path = root / f"decompressed.{version}.z64"
        if not path.is_file():
            continue
        ctl, tbl = slice_soundfont(path.read_bytes(), version)
        return load_clips(ctl, tbl), path.name
    return (), "none"


def render_header(clips: tuple[FootClip, ...], source: str) -> str:
    by_id = {clip.sfx_id: clip for clip in clips}
    lines = [
        "/* Generated by tools/banjo3ds/footstep_asset.py.",
        " * Local build output. Do not commit.",
        f" * source: {source}",
        " * one-shot PCM16 for D_80368DF0. A missing id is a zero-length slot.",
        " */",
        "#ifndef GENERATED_SFX_FOOT_H",
        "#define GENERATED_SFX_FOOT_H",
        f"#define BANJO_FOOT_PCM_COUNT {len(FOOT_SFX_IDS)}",
    ]
    symbols = []
    for index, sfx_id in enumerate(FOOT_SFX_IDS):
        macro = f"BANJO_FOOT_SFX_{index}"
        symbol = f"banjo_foot_sfx_{index}_pcm"
        clip = by_id.get(sfx_id)
        blob = b"" if clip is None else clip.blob
        known = clip is not None and clip.attack_volume is not None and clip.sample_volume is not None
        key_base = 60 if clip is None or clip.key_base is None else clip.key_base
        detune = 0 if clip is None or clip.detune is None else clip.detune
        omit = 0 if clip is None else clip.omit_detune
        attack = 0 if not known or clip is None or clip.attack_volume is None else clip.attack_volume
        sample = 0 if not known or clip is None or clip.sample_volume is None else clip.sample_volume
        lines.append(f"#define {macro}_ID 0x{sfx_id:x}")
        lines.append(f"#define {macro}_VOLUME_KNOWN {1 if known else 0}")
        lines.append(f"#define {macro}_ATTACK_VOLUME {attack}")
        lines.append(f"#define {macro}_SAMPLE_VOLUME {sample}")
        lines.append(f"#define {macro}_KEY_BASE {key_base}")
        lines.append(f"#define {macro}_DETUNE {detune}")
        lines.append(f"#define {macro}_OMIT_DETUNE {omit}")
        if not blob:
            lines.append(f"#define {macro}_PRESENT 0")
            lines.append(f"#define {macro}_PCM_BYTES 0")
            lines.append(f"static const unsigned char {symbol}[1] = {{0}};")
        else:
            lines.append(f"#define {macro}_PRESENT 1")
            lines.append(f"#define {macro}_PCM_BYTES {len(blob)}")
            lines.append(f"static const unsigned char {symbol}[{macro}_PCM_BYTES] = {{")
            for offset in range(0, len(blob), 16):
                chunk = ", ".join(f"0x{byte:02x}" for byte in blob[offset:offset + 16])
                lines.append(f"    {chunk},")
            lines.append("};")
        symbols.append(symbol)
    lines.append("static const struct {")
    lines.append("    int sfx_id;")
    lines.append("    int present;")
    lines.append("    int bytes;")
    lines.append("    int volume_known;")
    lines.append("    int attack_volume;")
    lines.append("    int sample_volume;")
    lines.append("    int key_base;")
    lines.append("    int detune;")
    lines.append("    int omit_detune;")
    lines.append("    const unsigned char *pcm;")
    lines.append("} banjo_foot_pcm[BANJO_FOOT_PCM_COUNT] = {")
    for index, symbol in enumerate(symbols):
        macro = f"BANJO_FOOT_SFX_{index}"
        lines.append(
            "    {"
            f"{macro}_ID, {macro}_PRESENT, {macro}_PCM_BYTES, "
            f"{macro}_VOLUME_KNOWN, {macro}_ATTACK_VOLUME, {macro}_SAMPLE_VOLUME, "
            f"{macro}_KEY_BASE, {macro}_DETUNE, {macro}_OMIT_DETUNE, {symbol}"
            "},"
        )
    lines.append("};")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def describe_clips(clips: tuple[FootClip, ...]) -> str:
    present = {clip.sfx_id for clip in clips}
    parts = []
    for sfx_id in FOOT_SFX_IDS:
        clip = next((item for item in clips if item.sfx_id == sfx_id), None)
        if clip is None:
            parts.append(f"sfx {sfx_id:#x} absent")
        else:
            parts.append(
                f"sfx {sfx_id:#x} bytes {len(clip.blob)} key {clip.key_base} detune {clip.detune}"
            )
    missing = [f"{sfx_id:#x}" for sfx_id in FOOT_SFX_IDS if sfx_id not in present]
    if missing:
        parts.append("missing " + ",".join(missing))
    return "; ".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the local walking-footstep PCM header."
    )
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    parser.add_argument("--rom", type=Path)
    parser.add_argument("--version", choices=supported_versions())
    parser.add_argument("--ctl", type=Path)
    parser.add_argument("--tbl", type=Path)
    parser.add_argument("--require", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    anchor = REPO_ROOT if args.out.is_absolute() else root
    try:
        header_path = resolve_header_path(args.out, anchor)
    except SfxBankError as error:
        print(f"sfx-foot: {error}", file=sys.stderr)
        return 1
    source = "none"
    clips: tuple[FootClip, ...] = ()
    try:
        if args.ctl is not None or args.tbl is not None:
            if args.ctl is None or args.tbl is None:
                raise SfxBankError("ctl and tbl are required together")
            if not args.ctl.is_file() or not args.tbl.is_file():
                raise SfxBankError("missing soundfont ctl or tbl")
            clips = load_clips(args.ctl.read_bytes(), args.tbl.read_bytes())
            source = f"ctl {args.ctl.name}"
        elif args.rom is not None:
            if args.version is None:
                raise SfxBankError("a ROM requires a version")
            if not args.rom.is_file():
                raise SfxBankError(f"missing decompressed ROM: {args.rom}")
            clips = load_clips(*slice_soundfont(args.rom.read_bytes(), args.version))
            source = args.rom.name
        else:
            clips, source = load_rom_clips(root)
        if args.require and len(clips) != len(FOOT_SFX_IDS):
            raise SfxBankError("one or more footstep sounds are missing")
        write_header(header_path, render_header(clips, source))
    except SfxBankError as error:
        if args.require:
            print(f"sfx-foot: {error}", file=sys.stderr)
            return 1
        write_header(header_path, render_header((), "none"))
        print(f"sfx-foot: {error}; the 3DS build will run without that footstep", file=sys.stderr)
        return 0
    print(f"sfx-foot: {source} {describe_clips(clips)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
