"""Generate the gitignored SFX_19-then-SFX_18 header for the 3DS listening probe.

The header lands in platform/3ds/build or the repository build directory.
PCM bytes stay out of Git. A missing ROM or soundfont writes a zero-length
asset and exits 0, so the 3DS build still runs. Playback order is SFX_19,
400 ms of silence, then unlooped SFX_18. Both clips are 22000 Hz PCM16.
"""

from __future__ import annotations

import argparse
import array
import sys
from dataclasses import dataclass
from pathlib import Path

from tools.banjo3ds.sfx_bank import (
    SFX_18_BIGBUTT_SLIDE,
    SFX_19_BANJO_LANDING_08,
    SfxBankError,
    extract_sfx,
    resolve_output_path,
    slice_soundfont,
    supported_versions,
)

# Must match tools/banjo3ds/sfx_probe/sfx_probe.h.
# 22000 Hz is the N64 AI output clock, not the bank field 22050 or loudness 28000.
SFX_PROBE_RATE = 22000
SFX_PROBE_GAP_MS = 400
_PROBE_HEADER = Path(__file__).resolve().parent / "sfx_probe" / "sfx_probe.h"
_PROBE_HEADER_TEXT = _PROBE_HEADER.read_text(encoding="utf-8")
if f"#define SFX_PROBE_RATE {SFX_PROBE_RATE}" not in _PROBE_HEADER_TEXT:
    raise RuntimeError("SFX_PROBE_RATE does not match tools/banjo3ds/sfx_probe/sfx_probe.h")
if f"#define SFX_PROBE_GAP_MS {SFX_PROBE_GAP_MS}" not in _PROBE_HEADER_TEXT:
    raise RuntimeError("SFX_PROBE_GAP_MS does not match tools/banjo3ds/sfx_probe/sfx_probe.h")

REPO_ROOT = Path(__file__).resolve().parents[2]
HEADER_ROOTS = (
    REPO_ROOT / "build",
    REPO_ROOT / "platform" / "3ds" / "build",
)
PCM19_NAME = Path("build") / "sfx" / "sfx_0019.pcm16"
PCM18_NAME = Path("build") / "sfx" / "sfx_0018.pcm16"
CLIP_ORDER = (
    (SFX_19_BANJO_LANDING_08, PCM19_NAME, "BANJO_SFX19", "banjo_sfx19_pcm"),
    (SFX_18_BIGBUTT_SLIDE, PCM18_NAME, "BANJO_SFX18", "banjo_sfx18_pcm"),
)


@dataclass(frozen=True)
class ProbeClip:
    sfx_id: int
    blob: bytes
    source: str
    sound_index: int | None


def resolve_header_path(path: Path, root: Path) -> Path:
    resolved = path.resolve() if path.is_absolute() else (root / path).resolve()
    if not any(resolved == allowed or allowed in resolved.parents for allowed in HEADER_ROOTS):
        raise SfxBankError(
            "SFX probe header must stay inside build/ or platform/3ds/build/"
        )
    return resolved


def pcm_bytes(samples: list[int]) -> bytes:
    encoded = array.array("h", samples)
    if sys.byteorder != "little":
        encoded.byteswap()
    return encoded.tobytes()


def usable_pcm(blob: bytes) -> bool:
    if len(blob) < 2 or len(blob) % 2 != 0:
        return False
    return any(blob[index : index + 2] != b"\x00\x00" for index in range(0, len(blob), 2))


def _decode_pair(ctl: bytes, tbl: bytes, label: str) -> tuple[ProbeClip, ...]:
    clips = []
    for sfx_id, _pcm_name, _macro, _symbol in CLIP_ORDER:
        info, samples = extract_sfx(ctl, tbl, sfx_id)
        if info.sound_index != sfx_id:
            raise SfxBankError(
                f"SFX {sfx_id:#x} selected soundArray index {info.sound_index:#x}"
            )
        if info.peak_abs == 0:
            raise SfxBankError(f"decoded SFX {sfx_id:#x} PCM is silent")
        blob = pcm_bytes(samples)
        if not usable_pcm(blob):
            raise SfxBankError(f"decoded SFX {sfx_id:#x} PCM is not a usable PCM16 buffer")
        clips.append(ProbeClip(sfx_id, blob, label, info.sound_index))
    return tuple(clips)


def _fallback_clips(root: Path) -> tuple[ProbeClip, ...]:
    clips = []
    for sfx_id, pcm_name, _macro, _symbol in CLIP_ORDER:
        path = root / pcm_name
        if not path.is_file():
            continue
        blob = path.read_bytes()
        if usable_pcm(blob):
            clips.append(ProbeClip(sfx_id, blob, path.as_posix(), None))
    return tuple(clips)


def _emit_clip(lines: list[str], macro: str, symbol: str, blob: bytes) -> None:
    if not blob:
        lines.extend(
            [
                f"#define {macro}_PRESENT 0",
                f"#define {macro}_PCM_BYTES 0",
                f"static const unsigned char {symbol}[1] = {{0}};",
            ]
        )
        return
    lines.append(f"#define {macro}_PRESENT 1")
    lines.append(f"#define {macro}_PCM_BYTES {len(blob)}")
    lines.append(f"static const unsigned char {symbol}[{macro}_PCM_BYTES] = {{")
    for offset in range(0, len(blob), 16):
        chunk = ", ".join(f"0x{byte:02x}" for byte in blob[offset : offset + 16])
        lines.append(f"    {chunk},")
    lines.append("};")


def render_header(clips: tuple[ProbeClip, ...], source: str) -> str:
    by_id = {clip.sfx_id: clip.blob for clip in clips}
    landing = by_id.get(SFX_19_BANJO_LANDING_08, b"")
    slide = by_id.get(SFX_18_BIGBUTT_SLIDE, b"")
    lines = [
        "/* Generated by tools/banjo3ds/sfx_probe_asset.py.",
        " * Local build output. Do not commit.",
        f" * source: {source}",
        f" * sfx_0019_bytes: {len(landing)}",
        f" * sfx_0018_bytes: {len(slide)}",
        f" * rate_hz: {SFX_PROBE_RATE}",
        f" * gap_ms: {SFX_PROBE_GAP_MS}",
        " * order: sfx 0x19, silence, unlooped sfx 0x18",
        " */",
        "#ifndef GENERATED_SFX_PROBE_H",
        "#define GENERATED_SFX_PROBE_H",
    ]
    for sfx_id, _pcm_name, macro, symbol in CLIP_ORDER:
        _emit_clip(lines, macro, symbol, by_id.get(sfx_id, b""))
    lines.extend(
        [
            "#define BANJO_SFX19_INDEX 0x19",
            "#define BANJO_SFX18_INDEX 0x18",
            "#define BANJO_SFX_PROBE_RATE_HZ 22000",
            "#define BANJO_SFX_PROBE_GAP_MS 400",
            '_Static_assert(BANJO_SFX19_INDEX == 0x19, "SFX_19 selects soundArray index 0x19");',
            '_Static_assert(BANJO_SFX18_INDEX == 0x18, "SFX_18 selects soundArray index 0x18");',
            '_Static_assert(BANJO_SFX_PROBE_RATE_HZ == 22000, "both clips play at 22000 Hz");',
            '_Static_assert(BANJO_SFX_PROBE_GAP_MS == 400, "the listening gap is 400 ms");',
            '_Static_assert(BANJO_SFX19_PCM_BYTES == 0 || (BANJO_SFX19_PCM_BYTES % 2) == 0, "SFX_19 PCM16");',
            '_Static_assert(BANJO_SFX18_PCM_BYTES == 0 || (BANJO_SFX18_PCM_BYTES % 2) == 0, "SFX_18 PCM16");',
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def describe_clips(clips: tuple[ProbeClip, ...]) -> str:
    parts = []
    for clip in clips:
        index = "fallback" if clip.sound_index is None else f"index {clip.sound_index:#x}"
        parts.append(f"sfx {clip.sfx_id:#x} {index} bytes {len(clip.blob)}")
    return "; ".join(parts)


def load_pcm(root: Path, rom: Path | None, version: str | None,
             ctl_path: Path | None, tbl_path: Path | None,
             allow_fallback: bool) -> tuple[tuple[ProbeClip, ...], str]:
    if ctl_path is not None or tbl_path is not None:
        if ctl_path is None or tbl_path is None:
            raise SfxBankError("ctl and tbl are required together")
        if not ctl_path.is_file() or not tbl_path.is_file():
            raise SfxBankError("missing soundfont ctl or tbl")
        clips = _decode_pair(
            ctl_path.read_bytes(), tbl_path.read_bytes(), f"ctl {ctl_path.name}"
        )
        return clips, clips[0].source
    if rom is not None:
        if version is None:
            raise SfxBankError("a ROM requires a version")
        if not rom.is_file():
            raise SfxBankError(f"missing decompressed ROM: {rom}")
        label = f"decompressed.{version}.z64"
        clips = _decode_pair(*slice_soundfont(rom.read_bytes(), version), label)
        return clips, label
    # us.v10 is listed before pal. The first ROM that exists wins.
    # A corrupt first ROM raises before a later ROM or the PCM fallback.
    for candidate in supported_versions():
        path = root / f"decompressed.{candidate}.z64"
        if path.is_file():
            clips = _decode_pair(*slice_soundfont(path.read_bytes(), candidate), path.name)
            return clips, path.name
    if allow_fallback:
        clips = _fallback_clips(root)
        if clips:
            return clips, "fallback"
    return (), "none"


def write_header(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(text, encoding="utf-8")
    temporary.replace(path)


def _write_pcm(path: Path, blob: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_bytes(blob)
    temporary.replace(path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the local SFX_19 then unlooped SFX_18 3DS probe header."
    )
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    parser.add_argument("--rom", type=Path)
    parser.add_argument("--version", choices=supported_versions())
    parser.add_argument("--ctl", type=Path)
    parser.add_argument("--tbl", type=Path)
    parser.add_argument("--pcm18", type=Path, help="Also write SFX_18 PCM16 inside build/")
    parser.add_argument("--pcm19", type=Path, help="Also write SFX_19 PCM16 inside build/")
    parser.add_argument("--no-fallback", action="store_true")
    parser.add_argument("--require", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    # Absolute --out is the 3DS makefile path. Relative --out is anchored at --root.
    anchor = REPO_ROOT if args.out.is_absolute() else root
    try:
        header_path = resolve_header_path(args.out, anchor)
    except SfxBankError as error:
        print(f"sfx-probe: {error}", file=sys.stderr)
        return 1
    try:
        pcm_paths = {
            SFX_18_BIGBUTT_SLIDE: resolve_output_path(args.pcm18) if args.pcm18 is not None else None,
            SFX_19_BANJO_LANDING_08: resolve_output_path(args.pcm19) if args.pcm19 is not None else None,
        }
        clips, source = load_pcm(
            root, args.rom, args.version, args.ctl, args.tbl, not args.no_fallback
        )
        if not clips:
            raise SfxBankError("no usable SFX_19 or SFX_18 asset")
        write_header(header_path, render_header(clips, source))
        for clip in clips:
            pcm_path = pcm_paths[clip.sfx_id]
            if pcm_path is not None:
                _write_pcm(pcm_path, clip.blob)
    except SfxBankError as error:
        if args.require:
            print(f"sfx-probe: {error}", file=sys.stderr)
            return 1
        write_header(header_path, render_header((), "none"))
        print(f"sfx-probe: {error}; the 3DS build will run without the probe", file=sys.stderr)
        return 0
    print(
        f"sfx-probe: {source} {describe_clips(clips)} "
        f"rate {SFX_PROBE_RATE} gap {SFX_PROBE_GAP_MS}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
